POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "premiuasd3",
    "password": "GBLtTyqUNjFnpo9m6"
}

###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "premium-jim",
    "password": "GBLtTyq3E_UNjFnpo9m6"
}

###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "basic-thomas",
    "password": "sR-_pcoow-27-6PAwCD8"
}

###

GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQzNCwibmFtZSI6IlByZW1pdW0gSmltIiwicm9sZSI6InByZW1pdW0iLCJpYXQiOjE2MjE0NTk1OTcsImV4cCI6MTYyMTQ2MTM5NywiaXNzIjoiaHR0cHM6Ly93d3cubmV0Z3VydS5jb20vIiwic3ViIjoiNDM0In0.8M4M5ojuzP65yNjRhaTIRBVSBTP6jA6TUgCUAO1_Abo

###

POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQzNCwibmFtZSI6IlByZW1pdW0gSmltIiwicm9sZSI6InByZW1pdW0iLCJpYXQiOjE2MjE0NjM2NTcsImV4cCI6MTYyMTQ2NTQ1NywiaXNzIjoiaHR0cHM6Ly93d3cubmV0Z3VydS5jb20vIiwic3ViIjoiNDM0In0.MJw7y8cJvSOgFZYlk-7RB8pxQ7zX1wia6hMan8BCUtg

{
    "title": "beyond"
}